# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "cylinder_asym"

  output_shape:
    - 480
    - 360
    - 20

  fea_dim: 9
  out_fea_dim: 256
  num_class: 17
  num_input_features: 16
  use_norm: True
  init_size: 20


###################
## Dataset options
dataset_params:
  dataset_type: "cylinder_dataset_nuscenes"
  pc_dataset_type: "SemKITTI_nusc"
  ignore_label: 0
  return_test: False
  fixed_volume_space: True
  label_mapping: "/workspace/segmenters/Cylinder3D/config/label_mapping/nuscenes.yaml"
  max_volume_space:
    - 50
    - 3.1415926
    - 3
  min_volume_space:
    - 0
    - -3.1415926
    - -5


###################
## Data_loader options
train_data_loader:
  data_path: "/workspace/data/nuScenes/"
  imageset: "/workspace/data/nuScenes/nuscenes_infos_train.pkl"
  return_ref: True
  batch_size: 2
  shuffle: True
  num_workers: 10

val_data_loader:
  data_path: "/workspace/data/nuScenes/"
  imageset: "/workspace/data/nuScenes/nuscenes_infos_val.pkl"
  return_ref: True
  batch_size: 1
  shuffle: False
  num_workers: 10


###################
## Train params
train_params:
  model_load_path: "/workspace/results/Cylinder3D/nuScenes/model_load.pt"
  model_save_path: "/workspace/results/Cylinder3D/nuScenes/model_save.pt"
  checkpoint_every_n_steps: 4599
  max_num_epochs: 40
  eval_every_n_steps: 4599
  learning_rate: 0.001
